import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';
import SectionTitle from '../component/section-title/section-title';
import { CategoryIcon02 } from '../component/category-icon';

import DigitalCreativeImg from '../assets/images/about/06.webp';
import Button from '../component/button/button';

const NumberList = [
	{ id: 1, item: 'Technical analysis', num: '01' },
	{ id: 2, item: 'Planning and Idea', num: '02' },
	{ id: 3, item: ' Design and Copywriting', num: '03' },
	{ id: 4, item: 'Front- &amp; Back-End Coding', num: '04' },
	{ id: 5, item: 'Testing and Launch', num: '05' },
];

function DigitalCreative() {
	return (
		<>
			<section className="section-pb">
				<Container>
					<Row className="g-0">
						<Col lg={9} className="creative-agency-box">
							<div className="bg-primary p-5">
								<SectionTitle
									extraClass="section-title-light"
									title="Digital creative agency"
									content="See some of the industries we have vast experience working in as a full-service marketing agency."
								/>
								<div className="category-style-03">
									<CategoryIcon02
										titleextraClass="text-white"
										iconextraClass="text-white mb-0"
										icon="flaticon-car"
										title="Automotive"
									/>
									<CategoryIcon02
										titleextraClass="text-white"
										iconextraClass="text-white mb-0"
										icon="flaticon-icon-626443"
										title="Retail"
									/>
									<CategoryIcon02
										titleextraClass="text-white"
										iconextraClass="text-white mb-0"
										icon="flaticon-author"
										title="Education"
									/>
									<CategoryIcon02
										titleextraClass="text-white"
										iconextraClass="text-white mb-0"
										icon="flaticon-classified"
										title="Publishing"
									/>
									<CategoryIcon02
										titleextraClass="text-white"
										iconextraClass="text-white mb-0"
										icon="flaticon-heart"
										title="Healthcare"
									/>
								</div>
							</div>
						</Col>
						<Col lg={3}>
							<div className="p-0 ps-lg-5">
								<SectionTitle
									extraClass="text-start mt-5"
									title="Have a Project?"
									content="Tell us about your idea, and we'll make it happen."
								/>
								<Button
									btnClass="btn-primary-round"
									btnText="Get a Quote"
									btnURL="/contact"
								/>
							</div>
						</Col>
					</Row>
					<Row className="g-0 pb-4 pb-md-0">
						<Col lg={9}>
							<Row>
								<Col md={6} className="mt-5">
									<img className="img-fluid" src={DigitalCreativeImg} alt="" />
								</Col>
								<Col md={6} className="mt-5">
									<div className="pe-3">
										<h3>Our work process</h3>
										<p>
											The following outlines our web-development process, which
											can be split into several sensible elements:
										</p>
										<ul className="list-unstyled list-number">
											{NumberList.map((list, index) => (
												<li key={index} className="d-flex mb-2">
													<span className="me-2">{list.num}</span>
													<p className="mb-0">{list.item}</p>
												</li>
											))}
										</ul>
									</div>
								</Col>
							</Row>
						</Col>
						<Col lg={3}>
							<div className="bg-secondary p-5 text-center h-100 mt-lg-0 mt-5">
								<div className="badge-round mt-2">
									<h4 className="text-white">
										<span className="d-block font-xlll">30+</span> Million
									</h4>
								</div>
								<p className="mt-3 text-white">
									Revenue generated by our partner and clients since 2005
								</p>
								<a
									className="btn btn-link link-primary mt-3"
									href="/case-study"
								>
									View Case Study
								</a>
							</div>
						</Col>
					</Row>
				</Container>
			</section>
		</>
	);
}
export default DigitalCreative;
